version: '3'
services:
  php-api:
    build: .
    ports:
      - "8087:80"
    volumes:
      - user-data:/var/www/html/data
    restart: unless-stopped

volumes:
  user-data:  # Именованный том Docker