version: '3'
services:
  php-api:
    image: php-rest-api
    ports:
      - "8087:80"
    volumes:
      - user-:/var/www/html/data 
      - ./ .env:/var/www/html/ .env
    restart: unless-stopped

volumes:
  user-: 